# Generated by Django 4.1.2 on 2022-10-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
